### ISSUE TITLE
Rename screensaver

### ISSUE THREAD

**Issue by svenjacobs** [winterbe/github-matrix-screensaver#1]
The screensaver appears as "Web" under system preferences.
Please rename it to "Matrix" or something else more descriptive.

**Comment by NetOpWibby** [comment]
Have you tried changing `<string>Web</string>` to `<string>Matrix</string>` in `Info.plist`?

**Comment by winterbe** [comment]
Thanks for the hint. Feel free to provide a pull request.

Am Samstag, 20. August 2016 schrieb ポール ウェッブ :
