### ISSUE TITLE
Cannot quit screen saver with mouse cursor moving

### ISSUE THREAD

**Issue by weichuliu** [winterbe/github-matrix-screensaver#10]
Seems like I can only quit screen saver using `esc`.

I'll be nice if I can also quit with mouse movement.

**Comment by blunck2** [comment]
How were you able to install the screensaver?  When I click on "Web.saver" I don't see "Matrix" in my "Screen Saver" System Preferences.

**Comment by weichuliu** [comment]
Throw the Web.saver under `~/Library/Screen Savers` and it should be recognized by system

**Comment by blunck2** [comment]
That worked.  Thanks!
