### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by rohinshanker** [winterbe/github-matrix-screensaver#22]
Screensaver worked for some time but as of a couple months ago it stopped working. The initial screen where all the text flashes works, but beyond that there's just a black screen. Maybe an issue w the web API?

**Comment by yousefabuz17** [comment]
yea same exact issue sadly.

**Comment by ajamesl** [comment]
Same issue here

**Comment by rohinshanker** [comment]
Updated my laptop and looks like its running again. I do have this process constantly running in my activity monitor but I don't think it's too big of a deal


<img width="671" alt="Screenshot 2024-01-31 at 12 47 50" src="https://github.com/winterbe/github-matrix-screensaver/assets/58312159/6cf9646a-0884-45df-912b-f934923f7299">

**Comment by yousefabuz17** [comment]
Awesome yea its working now thank you. Is there a way to make this a local supportive file so its not fully dependable?
