### ISSUE TITLE
The "rainy" matrix screen doesn't show up when my MBP is offline

### ISSUE THREAD

**Issue by robertchong** [winterbe/github-matrix-screensaver#5]
Hi, 

I've installed your latest 9/7 version to my MBP running on macOS v.10.12 Sierra. The matrix screensaver works fine when my MBP is connected, but when it's offline after the "numeric digit" screen (similar to [this](http://images4.fanpop.com/image/photos/23900000/-The-Matrix-the-matrix-23939784-1360-768.jpg)) appears, the screen goes blank and I won't see the "rainy" screen (similar to [this](http://winterbe.com/image/matrix.png)).

**Comment by Cord-Thomas** [comment]
Isn't that because it's trying to pull commit information from github?   An enhancement might be to cache a few minutes worth of commits from the last run in case it cannot connect...

**Comment by winterbe** [comment]
It fetches data from the heroku backend which itself fetches data from github. That’s why an internet connection is required.
