### ISSUE TITLE
Screensaver Title in System Preferences

### ISSUE THREAD

**Issue by agarrharr** [winterbe/github-matrix-screensaver#6]
In System Preferences, this screensaver shows up as "Web". It would be awesome if it said the name of the screensaver instead.

![screen shot 2016-11-21 at 9 03 41 am](https://cloud.githubusercontent.com/assets/3266363/20489921/7d9da132-afc9-11e6-897c-c9bc2d606a0c.png)

**Comment by winterbe** [comment]
This should be fixed: https://github.com/winterbe/github-matrix-screensaver/issues/1
