### ISSUE TITLE
Preview Animation

### ISSUE THREAD

**Issue by agarrharr** [winterbe/github-matrix-screensaver#8]
For some reason the preview animation on the right is too big and it's cutting off part of the image/animation.

![screen shot 2016-11-21 at 9 03 41 am](https://cloud.githubusercontent.com/assets/3266363/20490010/ce019598-afc9-11e6-99f6-40e58ba6d72e.png)

**Comment by winterbe** [comment]
Yeah, but I don't have a clue how this could be fixed. The preview is automatically generated by MacOS.
